export enum AppEventType {
  MOBILE_DEVICES_CHANGED = 'MOBILE_DEVICES_CHANGED',
  SESSIONS_SNAPSHOT = 'SESSIONS_SNAPSHOT',
  SESSION_FINISHED = 'SESSION_FINISHED',
  SESSION_WAITING = 'SESSION_WAITING',
  SETTINGS_SAVED = 'SETTINGS_SAVED',
  UPDATE_STATUS = 'UPDATE_STATUS',
  USAGE_SNAPSHOT = 'USAGE_SNAPSHOT',
  USAGE_WARNING = 'USAGE_WARNING',
}
