export enum IpcChannelMapper {
  OS_GET_PLATFORM = 'os:get-platform',
  SCHEDULING_GET_INFO = 'scheduling:get-info',
  SCHEDULING_SET_ENABLED = 'scheduling:set-enabled',
  SESSIONS_FOCUS = 'sessions:focus',
  SESSIONS_GET_FOCUS_SUPPORT = 'sessions:get-focus-support',
  SESSIONS_GET_SNAPSHOT = 'sessions:get-snapshot',
  SESSIONS_INSTALL_FOCUS_TOOL = 'sessions:install-focus-tool',
  SESSIONS_LIST = 'sessions:list',
  SESSIONS_TEST_SSH_HOST = 'sessions:test-ssh-host',
  SESSIONS_UPDATE = 'sessions:update',
  SETTINGS_GET = 'settings:get',
  SETTINGS_SAVE = 'settings:save',
  SETTINGS_UPDATE = 'settings:update',
  TRIGGER_CLEAR_RUN_LOGS = 'trigger:clear-run-logs',
  TRIGGER_GET_RUN_LOGS = 'trigger:get-run-logs',
  TRIGGER_OS_INSPECT = 'trigger:os-inspect',
  TRIGGER_SET_ENABLED = 'trigger:set-enabled',
  UPDATE_GET_STATUS = 'update:get-status',
  UPDATE_OPEN_RELEASE = 'update:open-release',
  UPDATE_STATUS = 'update:status',
  USAGE_GET_SNAPSHOT = 'usage:get-snapshot',
  USAGE_REFRESH = 'usage:refresh',
  USAGE_REFRESH_TRACKER = 'usage:refresh-tracker',
  USAGE_SET_TRACKER_PAUSED = 'usage:set-tracker-paused',
  USAGE_UPDATE = 'usage:update',
}
